/*
 * Recipe
 * This is a back end API  for Recipe app
 *
 * OpenAPI spec version: 1.0.0
 * Contact: nillohitbanerjee@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.mendix.model;


import java.util.ArrayList;
import java.util.List;

/**
 * Categories
 */
public class Categories {
  private Long results = null;

  private List<Category> categories = null;

  public Categories results(Long results) {
    this.results = results;
    return this;
  }

   /**
   * Get results
   * @return results
  **/
  public Long getResults() {
    return results;
  }

  public void setResults(Long results) {
    this.results = results;
  }

  public Categories categories(List<Category> categories) {
    this.categories = categories;
    return this;
  }

  public Categories addCategoriesItem(Category categoriesItem) {
    if (this.categories == null) {
      this.categories = new ArrayList<Category>();
    }
    this.categories.add(categoriesItem);
    return this;
  }

   /**
   * Get categories
   * @return categories
  **/
  public List<Category> getCategories() {
    return categories;
  }

  public void setCategories(List<Category> categories) {
    this.categories = categories;
  }



  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Categories {\n");
    
    sb.append("    results: ").append(toIndentedString(results)).append("\n");
    sb.append("    categories: ").append(toIndentedString(categories)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

