/*
 * Recipe
 * This is a back end API  for Recipe app
 *
 * OpenAPI spec version: 1.0.0
 * Contact: nillohitbanerjee@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.mendix.model;


import java.util.List;

/**
 * Categories
 */
public class Categories {
  private int results ;

  private List<Category> cat = null;

  public Categories results(int results) {
    this.results = results;
    return this;
  }

  public List<Category> getCat() {
    return cat;
  }

  public void setCat(List<Category> cat) {
    this.cat = cat;
  }

  /**
   * Get results
   * @return results
  **/
  public int getResults() {
    return results;
  }

  public void setResults(int results) {
    this.results = results;
  }




  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Categories {\n");
    
    sb.append("    results: ").append(toIndentedString(results)).append("\n");
    sb.append("    categories: ").append(toIndentedString(cat)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

