/*
 * Recipe
 * This is a back end API  for Recipe app
 *
 * OpenAPI spec version: 1.0.0
 * Contact: nillohitbanerjee@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.mendix.model;

/**
 * Directions
 */
public class Directions {
  private String step = null;

  public Directions step(String step) {
    this.step = step;
    return this;
  }

   /**
   * Get step
   * @return step
  **/
  public String getStep() {
    return step;
  }

  public void setStep(String step) {
    this.step = step;
  }





  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Directions {\n");
    
    sb.append("    step: ").append(toIndentedString(step)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

