/*
 * Recipe
 * This is a back end API  for Recipe app
 *
 * OpenAPI spec version: 1.0.0
 * Contact: nillohitbanerjee@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.mendix.model;

import java.util.ArrayList;
import java.util.List;

/**
 * Ingredients
 */
public class Ingredients {

  private List<IngredientDiv> ingdiv = null;

  public Ingredients ingdiv(List<IngredientDiv> ingdiv) {
    this.ingdiv = ingdiv;
    return this;
  }

  public Ingredients addIngdivItem(IngredientDiv ingdivItem) {
    if (this.ingdiv == null) {
      this.ingdiv = new ArrayList<IngredientDiv>();
    }
    this.ingdiv.add(ingdivItem);
    return this;
  }

   /**
   * Get ingdiv
   * @return ingdiv
  **/
  public List<IngredientDiv> getIngdiv() {
    return ingdiv;
  }

  public void setIngdiv(List<IngredientDiv> ingdiv) {
    this.ingdiv = ingdiv;
  }



  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Ingredients {\n");
    
    sb.append("    ingdiv: ").append(toIndentedString(ingdiv)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

