/*
 * Recipe
 * This is a back end API  for Recipe app
 *
 * OpenAPI spec version: 1.0.0
 * Contact: nillohitbanerjee@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.mendix.model;

/**
 * Ingredient
 */
public class Ingredient {
  private Amount amt = null;

  private String item = null;

  public Ingredient amt(Amount amt) {
    this.amt = amt;
    return this;
  }

   /**
   * Get amt
   * @return amt
  **/
  public Amount getAmt() {
    return amt;
  }

  public void setAmt(Amount amt) {
    this.amt = amt;
  }

  public Ingredient item(String item) {
    this.item = item;
    return this;
  }

   /**
   * Get item
   * @return item
  **/
  public String getItem() {
    return item;
  }

  public void setItem(String item) {
    this.item = item;
  }



  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Ingredient {\n");
    
    sb.append("    amt: ").append(toIndentedString(amt)).append("\n");
    sb.append("    item: ").append(toIndentedString(item)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

