/*
 * Recipe
 * This is a back end API  for Recipe app
 *
 * OpenAPI spec version: 1.0.0
 * Contact: nillohitbanerjee@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.mendix.model;

import java.util.ArrayList;
import java.util.List;

/**
 * IngredientDiv
 */
public class IngredientDiv {
  private List<Ingredient> ing = null;

  private String title = null;

  public IngredientDiv ing(List<Ingredient> ing) {
    this.ing = ing;
    return this;
  }

  public IngredientDiv addIngItem(Ingredient ingItem) {
    if (this.ing == null) {
      this.ing = new ArrayList<Ingredient>();
    }
    this.ing.add(ingItem);
    return this;
  }

   /**
   * Get ing
   * @return ing
  **/
  public List<Ingredient> getIng() {
    return ing;
  }

  public void setIng(List<Ingredient> ing) {
    this.ing = ing;
  }

  public IngredientDiv title(String title) {
    this.title = title;
    return this;
  }

   /**
   * Get title
   * @return title
  **/
  public String getTitle() {
    return title;
  }

  public void setTitle(String title) {
    this.title = title;
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IngredientDiv {\n");
    
    sb.append("    ing: ").append(toIndentedString(ing)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

