/*
 * Recipe
 * This is a back end API  for Recipe app
 *
 * OpenAPI spec version: 1.0.0
 * Contact: nillohitbanerjee@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.mendix.model;

/**
 * RecipeHead
 */
public class RecipeHead {
  private String title = null;

  private Categories categories = null;

  private Long yield = null;

  public RecipeHead title(String title) {
    this.title = title;
    return this;
  }

   /**
   * Get title
   * @return title
  **/
  public String getTitle() {
    return title;
  }

  public void setTitle(String title) {
    this.title = title;
  }

  public RecipeHead categories(Categories categories) {
    this.categories = categories;
    return this;
  }

   /**
   * Get categories
   * @return categories
  **/
  public Categories getCategories() {
    return categories;
  }

  public void setCategories(Categories categories) {
    this.categories = categories;
  }

  public RecipeHead yield(Long yield) {
    this.yield = yield;
    return this;
  }

   /**
   * Get yield
   * @return yield
  **/
  public Long getYield() {
    return yield;
  }

  public void setYield(Long yield) {
    this.yield = yield;
  }





  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RecipeHead {\n");
    
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    categories: ").append(toIndentedString(categories)).append("\n");
    sb.append("    yield: ").append(toIndentedString(yield)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

