/*
 * Recipe
 * This is a back end API  for Recipe app
 *
 * OpenAPI spec version: 1.0.0
 * Contact: nillohitbanerjee@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.mendix.model;

import org.springframework.data.annotation.Id;

import java.util.Objects;

/**
 * Recipe
 */


public class Recipe {


  private String id =null;

  private Directions directions = null;

  private RecipeHead head = null;

  private Ingredients ingredients = null;

  public Recipe directions(Directions directions) {
    this.directions = directions;
    return this;
  }


  /**
   * Get directions
   * @return directions
   **/
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public Recipe id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get directions
   * @return directions
  **/
  public Directions getDirections() {
    return directions;
  }

  public void setDirections(Directions directions) {
    this.directions = directions;
  }

  public Recipe head(RecipeHead head) {
    this.head = head;
    return this;
  }

   /**
   * Get head
   * @return head
  **/
  public RecipeHead getHead() {
    return head;
  }

  public void setHead(RecipeHead head) {
    this.head = head;
  }

  public Recipe ingredients(Ingredients ingredients) {
    this.ingredients = ingredients;
    return this;
  }

   /**
   * Get ingredients
   * @return ingredients
  **/
  public Ingredients getIngredients() {
    return ingredients;
  }

  public void setIngredients(Ingredients ingredients) {
    this.ingredients = ingredients;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Recipe recipe = (Recipe) o;
    return Objects.equals(this.directions, recipe.directions) &&
        Objects.equals(this.head, recipe.head) &&
        Objects.equals(this.ingredients, recipe.ingredients);
  }

  @Override
  public int hashCode() {
    return Objects.hash(directions, head, ingredients);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Recipe {\n");
    
    sb.append("    directions: ").append(toIndentedString(directions)).append("\n");
    sb.append("    head: ").append(toIndentedString(head)).append("\n");
    sb.append("    ingredients: ").append(toIndentedString(ingredients)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

