/*
 * Recipe
 * This is a back end API  for Recipe app
 *
 * OpenAPI spec version: 1.0.0
 * Contact: nillohitbanerjee@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.mendix.model;

import java.util.ArrayList;
import java.util.List;

/**
 * Recipes
 */
public class Recipes {
  private Long results = null;

  private Long total = null;

  private List<Recipe> recipes = null;

  public Recipes results(Long results) {
    this.results = results;
    return this;
  }

   /**
   * Get results
   * @return results
  **/
  public Long getResults() {
    return results;
  }

  public void setResults(Long results) {
    this.results = results;
  }

  public Recipes total(Long total) {
    this.total = total;
    return this;
  }

   /**
   * Get total
   * @return total
  **/
  public Long getTotal() {
    return total;
  }

  public void setTotal(Long total) {
    this.total = total;
  }

  public Recipes recipes(List<Recipe> recipes) {
    this.recipes = recipes;
    return this;
  }

  public Recipes addRecipesItem(Recipe recipesItem) {
    if (this.recipes == null) {
      this.recipes = new ArrayList<>();
    }
    this.recipes.add(recipesItem);
    return this;
  }

   /**
   * Get recipes
   * @return recipes
  **/
  public List<Recipe> getRecipes() {
    return recipes;
  }

  public void setRecipes(List<Recipe> recipes) {
    this.recipes = recipes;
  }





  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Recipes {\n");
    
    sb.append("    results: ").append(toIndentedString(results)).append("\n");
    sb.append("    total: ").append(toIndentedString(total)).append("\n");
    sb.append("    recipes: ").append(toIndentedString(recipes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

