/*
 * Recipe
 * This is a back end API  for Recipe app
 *
 * OpenAPI spec version: 1.0.0
 * Contact: nillohitbanerjee@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.mendix.dbModel;

import javax.persistence.*;
import java.util.HashSet;
import java.util.Set;

/**
 * Recipe
 */

@Entity
@Table(name = "recipes")
public class Recipe {

  @Id
  @GeneratedValue(strategy = GenerationType.AUTO)
  private Long id =null;

  private String name;

  private String recipeJson;

  @ManyToMany(mappedBy = "recipes", fetch = FetchType.LAZY)
  private Set<Category> categories= new HashSet<>();

  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public String getRecipeJson() {
    return recipeJson;
  }

  public void setRecipeJson(String recipeJson) {
    this.recipeJson = recipeJson;
  }

  public Set<Category> getCategories() {
    return categories;
  }

  public void setCategories(Set<Category> categories) {
    this.categories = categories;
  }
}

